# Generated by Django 3.0.3 on 2020-07-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderspot', '0006_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezadopedido',
            name='telefono_cliente',
            field=models.IntegerField(),
        ),
    ]
