# Generated by Django 3.0.3 on 2020-06-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor')], default='Vendedor', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor')], default='Vendedor', max_length=15),
        ),
    ]
