# Generated by Django 3.0.3 on 2020-07-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200601_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='telefono',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=1),
        ),
    ]
